import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Ringo Mar",
};

const TermsOfService = () => {
  return (
    <div className="mx-auto max-w-4xl px-4 py-10 text-gray-800 dark:text-gray-50">
      <h1 className="mb-6 text-3xl font-bold">Terms of Service</h1>

      <p className="mb-4">
        Our Terms of Service were last updated on <strong>Mon May 19 2025 19:56:40 GMT-0400 (Atlantic Standard Time)</strong>.
      </p>
      <p className="mb-4">Please read these terms and conditions carefully before using Our Service.</p>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Interpretation and Definitions</h2>
      <h3 className="mt-6 mb-2 text-xl font-semibold">Interpretation</h3>
      <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 className="mt-6 mb-2 text-xl font-semibold">Definitions</h3>
      <p className="mb-4">For the purposes of these Terms of Service:</p>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>
          <strong>"Affiliate"</strong> means an entity that controls, is controlled by...
        </li>
        <li>
          <strong>"Company"</strong> refers to <strong>RingoMar</strong>.
        </li>
        <li>
          <strong>"Content"</strong> refers to content such as text, images...
        </li>
        <li>
          <strong>"Device"</strong> means any device that can access the Service...
        </li>
        <li>
          <strong>"Feedback"</strong> means feedback, innovations or suggestions...
        </li>
        <li>
          <strong>"Service"</strong> refers to the Website.
        </li>
        <li>
          <strong>"Terms of Service"</strong> (also referred as "Terms" or "Terms of Service" or TOS) mean these Terms of Service that form the entire agreement between You and the Company regarding the use of the Service. This Terms of Service Agreement was generated by{" "}
          <a href="https://www.termsfeed.com/blog/sample-terms-of-service-template/" className="text-blue-600 underline">
            TermsFeed Terms of Service Template
          </a>
          .
        </li>
        <li>
          <strong>"Third-party Social Media Service"</strong> means any services or content...
        </li>
        <li>
          <strong>"Website"</strong> refers to <strong>ringomar.com</strong>, accessible from <strong>https://ringomar.com</strong>.
        </li>
        <li>
          <strong>"You"</strong> means the individual accessing or using the Service...
        </li>
      </ul>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Acknowledgment</h2>
      <p className="mb-4">These are the Terms of Service governing the use of this Service and the agreement that operates between You and the Company...</p>
      <p className="mb-4">Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms...</p>
      <p className="mb-4">By accessing or using the Service You agree to be bound by these Terms...</p>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Content</h2>
      <h3 className="mt-6 mb-2 text-xl font-semibold">Your Right to Post Content</h3>
      <p className="mb-4">
        Our Service allows You to create Content. You are responsible for the Content that You create on the Service, including its legality, reliability, and appropriateness. By creating Content on the Service, You grant Us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You retain any and all of Your rights to any Content
        You submit, post or display on or through the Service and You are responsible for protecting those rights. You agree that this license includes the right for Us to make Your Content available to other users of the Service, who may also use Your Content subject to these Terms. You represent and warrant that: (i) the Content is Yours (You own it) or You have the right to use it and grant Us the rights and
        license as provided in these Terms, and (ii) the creating of Your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.
      </p>

      <h3 className="mt-6 mb-2 text-xl font-semibold">Content Restrictions</h3>
      <p className="mb-4">
        The Company is not responsible for the content of the Service's users. You expressly understand and agree that You are solely responsible for the Content and for all activity that occurs under your account, whether done so by You or any third person using Your account. You may not transmit any Content that is unlawful, offensive, upsetting, intended to disgust, threatening, libelous, defamatory, obscene or
        otherwise objectionable. Examples of such objectionable Content include, but are not limited to, the following:
      </p>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>Unlawful or promoting unlawful activity.</li>
        <li>Defamatory, discriminatory, or mean-spirited content, including references or commentary about religion, race, sexual orientation, gender, national/ethnic origin, or other targeted groups.</li>
        <li>Spam or unauthorized solicitation.</li>
        <li>Viruses, malware, or other destructive content.</li>
        <li>Infringement of intellectual property.</li>
        <li>Impersonation of any entity or person.</li>
        <li>Privacy violations.</li>
        <li>False information.</li>
      </ul>

      <h3 className="mt-6 mb-2 text-xl font-semibold">Content Backups</h3>
      <p className="mb-4">Although regular backups of Content are performed, the Company does not guarantee there will be no loss or corruption of data.</p>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company. The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused
        or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.
      </p>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Termination</h2>
      <p className="mb-4">
        We reserve the right to suspend or terminate your access to the website, Twitch bot, or Discord bot at any time, with or without prior notice, and without liability, for any reason, including but not limited to a violation of these Terms of Service, misuse of the bot or service, or behavior that may negatively impact system performance or other users. Upon termination, your right to access or use any part of
        the service will cease immediately. This includes, but is not limited to, the use of bot commands, automated features, generated data, and any associated integrations. If you wish to discontinue your use of the service, you may stop using it at any time. Voluntary discontinuation does not entitle you to any refund or compensation. We are not responsible for any loss of data, access, or functionality that may
        result from a suspension or termination.
      </p>

      <h2 className="mt-10 mb-4 text-2xl font-semibold">Limitation of Liability</h2>
      <p className="mb-4">
        You understand and agree that your use of our website, Twitch bot, and Discord bot is at your sole risk. The services are provided on an “as is” and “as available” basis. While we strive to maintain reliability and accuracy, the Company makes no warranties regarding the uptime, performance, availability, or accuracy of the data returned by our bots or website. Under no circumstances shall the Company, its
        developers, affiliates, or partners be liable for any indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of data, service interruptions, loss of access to Twitch or Discord functionality, or reputational harm resulting from:
      </p>

      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li> Errors or incorrect data generated or returned by the bot or website</li>
        <li> Misuse or misconfiguration of commands, APIs, or features</li>
        <li> Any failure or delay in delivering or processing data</li>
        <li> Third-party platform changes or outages (e.g., Twitch or Discord updates) that affect bot performance</li>
      </ul>
      <p>
        By using our services, you acknowledge that automated systems can behave unpredictably and that we are not liable for any unintended outputs or misuse of generated data. You are solely responsible for verifying the accuracy of any data before relying on it. To the fullest extent permitted by law, the total liability of the Company for any claim related to the use of the services shall not exceed the amount
        you paid, if any, for using the service during the twelve (12) months preceding the claim.
      </p>
    </div>
  );
};

export default TermsOfService;
